// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grpc/proto/analyzer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_grpc_proto_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type Problem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Severity       string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Recommendation string                 `protobuf:"bytes,3,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_grpc_proto_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_grpc_proto_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *Problem) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Problem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Problem) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problems      []*Problem             `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_grpc_proto_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeResponse) GetProblems() []*Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

var File_grpc_proto_analyzer_proto protoreflect.FileDescriptor

const file_grpc_proto_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x19grpc/proto/analyzer.proto\x12\banalyzer\"(\n" +
	"\x0eAnalyzeRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"g\n" +
	"\aProblem\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x0erecommendation\x18\x03 \x01(\tR\x0erecommendation\"@\n" +
	"\x0fAnalyzeResponse\x12-\n" +
	"\bproblems\x18\x01 \x03(\v2\x11.analyzer.ProblemR\bproblems2P\n" +
	"\x0eAnalyzeService\x12>\n" +
	"\aAnalyze\x12\x18.analyzer.AnalyzeRequest\x1a\x19.analyzer.AnalyzeResponseB\x19Z\x17config_analyzer/grpc/pbb\x06proto3"

var (
	file_grpc_proto_analyzer_proto_rawDescOnce sync.Once
	file_grpc_proto_analyzer_proto_rawDescData []byte
)

func file_grpc_proto_analyzer_proto_rawDescGZIP() []byte {
	file_grpc_proto_analyzer_proto_rawDescOnce.Do(func() {
		file_grpc_proto_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_analyzer_proto_rawDesc), len(file_grpc_proto_analyzer_proto_rawDesc)))
	})
	return file_grpc_proto_analyzer_proto_rawDescData
}

var file_grpc_proto_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_proto_analyzer_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: analyzer.AnalyzeRequest
	(*Problem)(nil),         // 1: analyzer.Problem
	(*AnalyzeResponse)(nil), // 2: analyzer.AnalyzeResponse
}
var file_grpc_proto_analyzer_proto_depIdxs = []int32{
	1, // 0: analyzer.AnalyzeResponse.problems:type_name -> analyzer.Problem
	0, // 1: analyzer.AnalyzeService.Analyze:input_type -> analyzer.AnalyzeRequest
	2, // 2: analyzer.AnalyzeService.Analyze:output_type -> analyzer.AnalyzeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_analyzer_proto_init() }
func file_grpc_proto_analyzer_proto_init() {
	if File_grpc_proto_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_analyzer_proto_rawDesc), len(file_grpc_proto_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_analyzer_proto_goTypes,
		DependencyIndexes: file_grpc_proto_analyzer_proto_depIdxs,
		MessageInfos:      file_grpc_proto_analyzer_proto_msgTypes,
	}.Build()
	File_grpc_proto_analyzer_proto = out.File
	file_grpc_proto_analyzer_proto_goTypes = nil
	file_grpc_proto_analyzer_proto_depIdxs = nil
}
